/* ============================================================
   DAR MAROC - GÉOLOCALISATION (utils/geo.js)
   Tous les pays internationaux + leurs grandes villes.
   Cascade "Pays -> Ville" pour le formulaire du dashboard.
   ============================================================ */
(function () {
  'use strict';

  var COUNTRIES = [
    { name: 'Maroc', cities: ['Agadir', 'Casablanca', 'Fès', 'Marrakech', 'Meknès', 'Oujda', 'Rabat', 'Tanger', 'Tétouan', 'Kénitra', 'El Jadida', 'Nador', 'Safi', 'Mohammedia', 'Béni Mellal', 'Taza', 'Khouribga', 'Essaouira', 'Ouarzazate', 'Laâyoune', 'Dakhla', 'Al Hoceïma', 'Guelmim', 'Tiznit', 'Taroudant', 'Errachidia', 'Ifrane', 'Azemmour', 'Chefchaouen', 'Settat', 'Berrechid', 'Larache', 'Sidi Ifni', 'Youssoufia', 'Skhirat', 'Temara', 'Bouskoura', 'Bir Guendouz', 'Sidi Kacem', 'Zagora', 'Boujdour', 'Sidi Slimane', 'Berkane', 'Midelt', 'Oued Zem'] },
    { name: 'France', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Montpellier', 'Strasbourg', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre', 'Saint-Étienne', 'Toulon', 'Grenoble', 'Dijon', 'Angers', 'Nîmes', 'Villeurbanne', 'Aix-en-Provence', 'Clermont-Ferrand', 'Limoges', 'Metz', 'Perpignan', 'Besançon', 'Orléans', 'Rouen', 'Mulhouse', 'Caen', 'Nancy', 'Amiens', 'Tours', 'Avignon', 'Brest', 'Poitiers', 'Annecy', 'Cannes', 'Antibes', 'Biarritz'] },
    { name: 'Belgique', cities: ['Bruxelles', 'Anvers', 'Gand', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Louvain', 'Mons', 'Ostende'] },
    { name: 'Suisse', cities: ['Zurich', 'Genève', 'Bâle', 'Lausanne', 'Berne', 'Winterthour', 'Lucerne', 'Saint-Gall', 'Lugano', 'Fribourg'] },
    { name: 'Canada', cities: ['Toronto', 'Montréal', 'Vancouver', 'Calgary', 'Ottawa', 'Edmonton', 'Québec', 'Winnipeg', 'Hamilton', 'Halifax'] },
    { name: 'Algérie', cities: ['Alger', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Sétif', 'Batna', 'Tlemcen', 'Béjaïa', 'Ouargla', 'Mostaganem', 'Skikda'] },
    { name: 'Tunisie', cities: ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte', 'Gabès', 'Ariana', 'Monastir', 'Djerba', 'Hammamet'] },
    { name: 'Mauritanie', cities: ['Nouakchott', 'Nouadhibou', 'Kiffa', 'Rosso', 'Kaédi', 'Zouerate', 'Atar', 'Sélibabi'] },
    { name: 'Sénégal', cities: ['Dakar', 'Touba', 'Thiès', 'Rufisque', 'Kaolack', 'Saint-Louis', 'Ziguinchor', 'Mbour', 'Diourbel'] },
    { name: 'Côte d\'Ivoire', cities: ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'San-Pédro', 'Korhogo', 'Man', 'Gagnoa'] },
    { name: 'Mali', cities: ['Bamako', 'Sikasso', 'Mopti', 'Ségou', 'Kayes', 'Gao', 'Tombouctou', 'Koutiala'] },
    { name: 'Niger', cities: ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Tahoua', 'Dosso', 'Diffa'] },
    { name: 'Tchad', cities: ['N\'Djaména', 'Moundou', 'Sarh', 'Abéché', 'Kélo', 'Koumra', 'Am Timan'] },
    { name: 'Égypte', cities: ['Le Caire', 'Alexandrie', 'Gizeh', 'Port-Saïd', 'Suez', 'Louxor', 'Assouan', 'Hurghada', 'Charm el-Cheikh', 'Ismaïlia'] },
    { name: 'Arabie saoudite', cities: ['Riyad', 'Djeddah', 'La Mecque', 'Médine', 'Dammam', 'Tabuk', 'Buraydah', 'Khobar'] },
    { name: 'Émirats arabes unis', cities: ['Dubaï', 'Abou Dabi', 'Charjah', 'Ajman', 'Ras el-Khaimah', 'Fujaïrah', 'Al Aïn'] },
    { name: 'Qatar', cities: ['Doha', 'Al Rayyan', 'Al Wakrah', 'Umm Salal', 'Lusail'] },
    { name: 'Koweït', cities: ['Koweït City', 'Hawalli', 'Salmiya', 'Al Ahmadi', 'Jahra'] },
    { name: 'Bahreïn', cities: ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Isa Town'] },
    { name: 'Oman', cities: ['Mascate', 'Salalah', 'Sohar', 'Nizwa', 'Sur', 'Ibri'] },
    { name: 'Jordanie', cities: ['Amman', 'Zarqa', 'Irbid', 'Aqaba', 'Mafraq', 'Karak', 'Salt'] },
    { name: 'Liban', cities: ['Beyrouth', 'Tripoli', 'Sidon', 'Tyr', 'Jounieh', 'Zahlé', 'Byblos'] },
    { name: 'Syrie', cities: ['Damas', 'Alep', 'Homs', 'Lattaquié', 'Hama', 'Raqqa', 'Deir ez-Zor'] },
    { name: 'Irak', cities: ['Bagdad', 'Bassora', 'Mossoul', 'Erbil', 'Najaf', 'Karbala', 'Kirkouk', 'Souleimaniye'] },
    { name: 'Iran', cities: ['Téhéran', 'Machhad', 'Ispahan', 'Chiraz', 'Tabriz', 'Ahvaz', 'Qom', 'Kermanchah'] },
    { name: 'Turquie', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Gaziantep', 'Konya', 'Mersin', 'Trabzon'] },
    { name: 'Espagne', cities: ['Madrid', 'Barcelone', 'Valence', 'Séville', 'Saragosse', 'Malaga', 'Bilbao', 'Alicante', 'Grenade', 'Palma de Majorque', 'Tenerife', 'Las Palmas'] },
    { name: 'Portugal', cities: ['Lisbonne', 'Porto', 'Braga', 'Coimbra', 'Faro', 'Funchal', 'Aveiro', 'Évora'] },
    { name: 'Italie', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Palerme', 'Gênes', 'Bologne', 'Florence', 'Venise', 'Vérone', 'Bari'] },
    { name: 'Allemagne', cities: ['Berlin', 'Hambourg', 'Munich', 'Cologne', 'Francfort', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dortmund', 'Essen', 'Brême', 'Dresde'] },
    { name: 'Royaume-Uni', cities: ['Londres', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Leeds', 'Sheffield', 'Édimbourg', 'Bristol', 'Newcastle'] },
    { name: 'Irlande', cities: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Kilkenny'] },
    { name: 'Pays-Bas', cities: ['Amsterdam', 'Rotterdam', 'La Haye', 'Utrecht', 'Eindhoven', 'Groningue', 'Tilbourg', 'Almere'] },
    { name: 'Luxembourg', cities: ['Luxembourg-Ville', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck'] },
    { name: 'Autriche', cities: ['Vienne', 'Graz', 'Linz', 'Salzbourg', 'Innsbruck', 'Klagenfurt'] },
    { name: 'Grèce', cities: ['Athènes', 'Thessalonique', 'Patras', 'Héraklion', 'Larissa', 'Volos', 'Rhodes'] },
    { name: 'Suède', cities: ['Stockholm', 'Göteborg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping'] },
    { name: 'Norvège', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Tromsø'] },
    { name: 'Danemark', cities: ['Copenhague', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers'] },
    { name: 'Finlande', cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä'] },
    { name: 'Pologne', cities: ['Varsovie', 'Cracovie', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz'] },
    { name: 'République tchèque', cities: ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc'] },
    { name: 'Slovaquie', cities: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra', 'Banská Bystrica'] },
    { name: 'Hongrie', cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr'] },
    { name: 'Roumanie', cities: ['Bucarest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov'] },
    { name: 'Bulgarie', cities: ['Sofia', 'Plovdiv', 'Varna', 'Bourgas', 'Roussé', 'Stara Zagora'] },
    { name: 'Croatie', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik'] },
    { name: 'Serbie', cities: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'] },
    { name: 'Ukraine', cities: ['Kiev', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Zaporijjia', 'Lviv'] },
    { name: 'Russie', cities: ['Moscou', 'Saint-Pétersbourg', 'Novossibirsk', 'Iekaterinbourg', 'Kazan', 'Nijni Novgorod', 'Tcheliabinsk', 'Samara'] },
    { name: 'Israël', cities: ['Jérusalem', 'Tel-Aviv', 'Haïfa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya'] },
    { name: 'États-Unis', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphie', 'San Antonio', 'San Diego', 'Dallas', 'San Francisco', 'Miami', 'Seattle', 'Boston', 'Las Vegas', 'Atlanta', 'Washington D.C.', 'Détroit', 'Denver'] },
    { name: 'Mexique', cities: ['Mexico', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Cancún', 'Mérida', 'León', 'Acapulco', 'Querétaro'] },
    { name: 'Brésil', cities: ['São Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'] },
    { name: 'Argentine', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Mar del Plata', 'Salta'] },
    { name: 'Chili', cities: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Viña del Mar', 'Temuco'] },
    { name: 'Colombie', cities: ['Bogota', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Pereira', 'Santa Marta'] },
    { name: 'Pérou', cities: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Cusco', 'Piura', 'Iquitos'] },
    { name: 'Venezuela', cities: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Mérida', 'Ciudad Guayana'] },
    { name: 'Équateur', cities: ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Machala', 'Manta'] },
    { name: 'Bolivie', cities: ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre', 'El Alto', 'Oruro'] },
    { name: 'Paraguay', cities: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Encarnación'] },
    { name: 'Uruguay', cities: ['Montevideo', 'Salto', 'Paysandú', 'Maldonado', 'Punta del Este'] },
    { name: 'Cuba', cities: ['La Havane', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara', 'Cienfuegos'] },
    { name: 'République dominicaine', cities: ['Saint-Domingue', 'Santiago de los Caballeros', 'La Romana', 'San Pedro de Macorís', 'Puerto Plata'] },
    { name: 'Honduras', cities: ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Choloma', 'Comayagua'] },
    { name: 'Guatemala', cities: ['Guatemala City', 'Quetzaltenango', 'Escuintla', 'Villa Nueva', 'Mixco'] },
    { name: 'Panama', cities: ['Panama City', 'Colón', 'David', 'La Chorrera', 'Santiago'] },
    { name: 'Costa Rica', cities: ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Liberia', 'Puntarenas'] },
    { name: 'Salvador', cities: ['San Salvador', 'Santa Ana', 'San Miguel', 'Soyapango', 'Mejicanos'] },
    { name: 'Nicaragua', cities: ['Managua', 'León', 'Masaya', 'Granada', 'Matagalpa'] },
    { name: 'Jamaïque', cities: ['Kingston', 'Montego Bay', 'Spanish Town', 'Portmore', 'Ocho Rios'] },
    { name: 'Haïti', cities: ['Port-au-Prince', 'Cap-Haïtien', 'Gonaïves', 'Les Cayes', 'Jacmel'] },
    { name: 'Inde', cities: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Ahmedabad', 'Pune', 'Jaipur', 'Goa'] },
    { name: 'Pakistan', cities: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Islamabad', 'Multan', 'Peshawar'] },
    { name: 'Bangladesh', cities: ['Dacca', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal'] },
    { name: 'Sri Lanka', cities: ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo', 'Anuradhapura'] },
    { name: 'Népal', cities: ['Katmandou', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Birgunj'] },
    { name: 'Indonésie', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Denpasar', 'Makassar'] },
    { name: 'Malaisie', cities: ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh', 'Malacca', 'Kuching', 'Kota Kinabalu'] },
    { name: 'Singapour', cities: ['Singapour'] },
    { name: 'Thaïlande', cities: ['Bangkok', 'Chiang Mai', 'Pattaya', 'Phuket', 'Hat Yai', 'Nakhon Ratchasima'] },
    { name: 'Vietnam', cities: ['Hanoï', 'Hô Chi Minh-Ville', 'Da Nang', 'Haïphong', 'Cần Thơ', 'Huế', 'Nha Trang'] },
    { name: 'Philippines', cities: ['Manille', 'Quezon City', 'Cebu', 'Davao', 'Zamboanga', 'Baguio'] },
    { name: 'Chine', cities: ['Pékin', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Chongqing', 'Wuhan', 'Xi\'an', 'Hangzhou', 'Nankin'] },
    { name: 'Japon', cities: ['Tokyo', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kyoto', 'Kobe', 'Yokohama', 'Hiroshima'] },
    { name: 'Corée du Sud', cities: ['Séoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon'] },
    { name: 'Corée du Nord', cities: ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo', 'Wonsan'] },
    { name: 'Taïwan', cities: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu', 'Keelung'] },
    { name: 'Mongolie', cities: ['Oulan-Bator', 'Erdenet', 'Darkhan', 'Choibalsan', 'Mörön'] },
    { name: 'Kazakhstan', cities: ['Almaty', 'Nour-Soultan', 'Chymkent', 'Karaganda', 'Aktioubé', 'Atyraou'] },
    { name: 'Ouzbékistan', cities: ['Tachkent', 'Samarcande', 'Boukhara', 'Namangan', 'Andijan', 'Noukous'] },
    { name: 'Afghanistan', cities: ['Kaboul', 'Kandahar', 'Hérat', 'Mazâr-e Charîf', 'Djâlâlâbâd'] },
    { name: 'Australie', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adélaïde', 'Canberra', 'Darwin', 'Hobart'] },
    { name: 'Nouvelle-Zélande', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin'] },
    { name: 'Afrique du Sud', cities: ['Johannesburg', 'Le Cap', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London'] },
    { name: 'Nigeria', cities: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City', 'Kaduna'] },
    { name: 'Ghana', cities: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Cape Coast'] },
    { name: 'Kenya', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika'] },
    { name: 'Tanzanie', cities: ['Dar es Salam', 'Dodoma', 'Mwanza', 'Arusha', 'Zanzibar', 'Mbeya'] },
    { name: 'Éthiopie', cities: ['Addis-Abeba', 'Dire Dawa', 'Mekele', 'Gondar', 'Bahir Dar', 'Awasa'] },
    { name: 'Cameroun', cities: ['Douala', 'Yaoundé', 'Garoua', 'Bamenda', 'Maroua', 'Bafoussam', 'Kribi'] },
    { name: 'Gabon', cities: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda'] },
    { name: 'République démocratique du Congo', cities: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Kananga', 'Goma', 'Bukavu'] },
    { name: 'Angola', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Lubango', 'Malanje'] },
    { name: 'Mozambique', cities: ['Maputo', 'Beira', 'Nampula', 'Matola', 'Chimoio'] },
    { name: 'Zimbabwe', cities: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru'] },
    { name: 'Zambie', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Livingstone', 'Chingola'] },
    { name: 'Botswana', cities: ['Gaborone', 'Francistown', 'Maun', 'Molepolole', 'Kasane'] },
    { name: 'Namibie', cities: ['Windhoek', 'Walvis Bay', 'Swakopmund', 'Rundu', 'Oshakati'] },
    { name: 'Libye', cities: ['Tripoli', 'Benghazi', 'Misrata', 'Tobrouk', 'Sebha', 'Zaouïa'] },
    { name: 'Soudan', cities: ['Khartoum', 'Omdurman', 'Port-Soudan', 'Kassala', 'El Obeid', 'Nyala'] },
    { name: 'Somali', cities: ['Mogadiscio', 'Hargeisa', 'Kismaayo', 'Bosaso', 'Baidoa'] },
    { name: 'Djibouti', cities: ['Djibouti', 'Ali Sabieh', 'Tadjourah', 'Obock', 'Dikhil'] },
    { name: 'Érythrée', cities: ['Asmara', 'Massawa', 'Assab', 'Keren', 'Mendefera'] },
    { name: 'Guinée', cities: ['Conakry', 'Kankan', 'Kindia', 'Labé', 'N\'Zérékoré'] },
    { name: 'Burkina Faso', cities: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora'] },
    { name: 'Bénin', cities: ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou', 'Abomey-Calavi'] },
    { name: 'Togo', cities: ['Lomé', 'Sokodé', 'Kara', 'Kpalimé', 'Atakpamé'] },
    { name: 'Cap-Vert', cities: ['Praia', 'Mindelo', 'Santa Maria', 'Assomada', 'São Filipe'] },
    { name: 'Madagascar', cities: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara'] },
    { name: 'Île Maurice', cities: ['Port-Louis', 'Beau Bassin', 'Curepipe', 'Quatre Bornes', 'Vacoas', 'Flic-en-Flac'] }
  ];

  function countryNames() {
    return COUNTRIES.map(function (c) { return c.name; });
  }

  function citiesOf(countryName) {
    for (var i = 0; i < COUNTRIES.length; i++) {
      if (COUNTRIES[i].name === countryName) return COUNTRIES[i].cities;
    }
    return [];
  }

  window.DarMarocGeo = {
    countries: COUNTRIES,
    countryNames: countryNames,
    citiesOf: citiesOf
  };
})();
